name: "Build and upload decomp tool binaries for the specifed platform"
description: "Builds and uploads a tarball with decomp tools for specified platform"

inputs:
    platform:
      required: true
      type: string
    install_llvm_build_deps_hook:
      required: true
      type: string
runs:
  using: "composite"
  steps:
    - name: Get tool versions
      id: versions
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          source /etc/os-release
          echo "os=${NAME// /-}-${VERSION_ID}" >> "$GITHUB_OUTPUT"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          echo "os=macOS-$(sw_vers -productVersion)" >> "$GITHUB_OUTPUT"
        fi
        echo "clang=$(clang --version | sed -n '1s/.*clang version \([0-9][0-9.]*\).*/\1/p')" >> "$GITHUB_OUTPUT"
        echo "cmake=$(cmake --version | sed -n '1s/^cmake version //p')" >> "$GITHUB_OUTPUT"
        echo "ninja=$(ninja --version)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Cache llvm tools
      uses: actions/cache@v6
      with:
        path: |
          download/cfe-3.9.1.src/build/bin/clang-3.9
          download/lld-3.9.1.src/build/tools/lld/lld
        key: ${{ inputs.platform }}_${{ steps.versions.outputs.os }}_clang-${{ steps.versions.outputs.clang }}_cmake-${{ steps.versions.outputs.cmake }}_ninja-${{ steps.versions.outputs.ninja }}_llvm-tools
    - name: Install llvm tools build dependencies if needed
      run: |
          if [ ! -f "download/cfe-3.9.1.src/build/bin/clang-3.9" ] || [ ! -f "download/lld-3.9.1.src/build/tools/lld/lld" ]; then
            eval "${{ inputs.install_llvm_build_deps_hook }}"
          fi
      shell: bash
    - name: Set up rust toolchain and caching
      uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
      with:
        cache: true
        cache-workspaces: nx-decomp-tools/viking
    - name: Generate prebuilt archives
      run: |
        # Add this to path from macos, needs to be done here so that it doesn't get reset between steps
        if [ "${{ inputs.platform }}" == "arm64-Darwin" ]; then
          export "PATH=$HOME/.pyenv/versions/2.7.18/bin:$PATH"
          export CC="/opt/homebrew/opt/llvm@19/bin/clang"
          export CXX="/opt/homebrew/opt/llvm@19/bin/clang++"
        fi

        ./generate.sh
      shell: bash
    - uses: actions/upload-artifact@v7
      with:
        name: LCUDecomp-binaries_${{ inputs.platform }}
        path: build/LCUDecomp-binaries_${{ inputs.platform }}.tar.xz
    - uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          build/LCUDecomp-binaries_${{ inputs.platform }}.tar.xz
        preserve_order: true
        fail_on_unmatched_files: true
